### ISSUE TITLE
Issue with updated ACMEv2 script

### ISSUE THREAD

**Issue by SI-BenHodges** [intelequia/letsencrypt-aw#2]
Hey,

Thank you for the updated ACMEv2 script as this is very handy, i no longer get the message saying ACMEv1 isn't supported.

I am getting this error however, which seems to be a new one for this script:

Server returned problem (Status: 403). @{type=urn:ietf:params:acme:error:orderNotReady; detail=Order's status ("invalid") is not acceptable for finalization; status=403} (Server returned problem (Status: 403). @{type=urn:ietf:params:acme:error:orderNotReady; detail=Order's status ("invalid") is not acceptable for finalization; status=403})

**Comment by NikolaiThingnesLeira** [comment]
Hi,
My application is usually behind a firewall so I decided to add a temporary opening during runtime and it works for me, might be the same for you?

I've migrated the entire script to use the Az module, which is why I'm using Az cmdlets here. If you use AzureRM you need to swap to the appropriate ones, or you can import the following modules for this specific use:
Az.Accounts
Az.Networking

And add the following snippet to your login ( After $connection )
```
# Ensures that no login info is saved after the runbook is done
Disable-AzContextAutosave

# Log in as the service principal from the Runbook
Login-AzAccount -ServicePrincipal -Tenant $connection.TenantID -ApplicationId $connection.ApplicationID -CertificateThumbprint $connection.CertificateThumbprint
```

To open the firewall:
```
# Temporarily open the firewall to allow outside requests
    # Workaround because the NSG cmdlet is buggy
    $nsg = Get-AzNetworkSecurityGroup -Name $NSGName -ResourceGroupName $STResourceGroupName
    ($nsg.SecurityRules | Where-Object { $_.Name -eq $NSGRule }).Access = "Allow"
    # Pushes the entire object
    $nsg | Set-AzNetworkSecurityGroup | Get-AzNetworkSecurityRuleConfig -Name $NSGRule | Format-Table -AutoSize
# Need to sleep for 30 seconds to ensure the rule is applied for new connections
Start-Sleep -Seconds 30
```

To close it at the end:
```
# Close the temporary opening in the firewall
    # Again a workaround for the NSG CMDlet
    $nsg = Get-AzNetworkSecurityGroup -Name $NSGName -ResourceGroupName $STResourceGroupName
    ($nsg.SecurityRules | Where-Object { $_.Name -eq $NSGRule }).Access = "Deny"
    # Pushing the entire object
    $nsg | Set-AzNetworkSecurityGroup | Get-AzNetworkSecurityRuleConfig -Name $NSGRule | Format-Table -AutoSize
```

Variables:
$STResourceGroupName - My NSG is in the same resourcegroup as the storage account, so I reused this variable
$NSGName - The name of the Network Security Group that enforces your inbound rules
$NGSRule - The name of the rule that you want to temporarily open. I added a 443 Deny which i switch to "Allow" for this purpose. Keep in mind you need to allow for Azure Resources on port 443 on a rule with a higher priority ( Lower number ) when you do this

**Comment by SI-BenHodges** [comment]
Hey Gholie,

I actually already have an allow rule on an NSG setup for the VM running the site as it is a web server so needs port 443 working.

nevertheless i added in what you said but just got loads of errors about az.network and az.accounts not being able to load.

And the error has now changed to:
Server returned problem (Status: 403).
@{type=urn:ietf:params:acme:error:orderNotReady; detail=Order's status ("pending") is not acceptable for finalization; status=403} (Server returned problem (Status: 403).
@{type=urn:ietf:params:acme:error:orderNotReady; detail=Order's status ("pending") is not acceptable for finalization; status=403})

i get the feeling it's got something to do with  this part in the script as it's basically not waiting for the correct response .. 
# Wait a little bit and update the order, until we see the states
while($order.Status -notin ("ready","invalid")) {
    Start-Sleep -Seconds 10;
    $order | Update-ACMEOrder $state -PassThru;
}

**Comment by NikolaiThingnesLeira** [comment]
So it allows all internet traffic on port 443? If so you won't need the things I added

**Comment by SI-BenHodges** [comment]
Yes that's right,
![image](https://user-images.githubusercontent.com/54708648/73454821-c8094f80-4366-11ea-9b81-a8d2a2730abd.png)


shouldn't it actually be this:
# Wait a little bit and update the order, until we see the states
while($order.Status -notin ("pending","processing","valid","invalid")) {
    Start-Sleep -Seconds 60;
    $order | Update-ACMEOrder $state -PassThru;
}
it needs the 'ready' response right? so you need to exclude all of the others

**Comment by NikolaiThingnesLeira** [comment]
Then I'm not sure what it is, altough I had the same exact error message as you did and it was because the application was behind a firewall.

One more suggestion: Is your blob container public? There should be an URL in your runbook output like this:
AbsoluteUrl : example.com/.well-known/acme-challenge/<somestring>

This one has to be reachable from anywhere

**Comment by NikolaiThingnesLeira** [comment]
And while the status of the order is "invalid" it can't process anymore, so the script does the right thing by stopping - atleast from my understanding of the process

**Comment by SI-BenHodges** [comment]
yes as far as i know it is. Here's a screen grab of the blob container:
![image](https://user-images.githubusercontent.com/54708648/73455806-ac9f4400-4368-11ea-8e72-655e7a4e400e.png)

it looks like it can access it as it is putting the files into the storage account:

![image](https://user-images.githubusercontent.com/54708648/73456225-6dbdbe00-4369-11ea-9ff1-0a86adb5d663.png)

here's the output from the acme authorization URL, it seems to say unauthorized and invalid response from https://dev.cwac.echoweb.co.uk/.well-known/acme-challenge/feY5z-DOOKfkF_mi5k_5S9OwbtD-pxH-P0TsekYunGM - but it is public?

https://acme-v02.api.letsencrypt.org/acme/authz-v3/2551832482

**Comment by NikolaiThingnesLeira** [comment]
Under configuration on your Storage Account, do you allow unsecure connections? ACME requests goes over HTTP, this is my setting (Secure Transfer required set to "Disabled":
![image](https://user-images.githubusercontent.com/8503265/73457054-5388dd80-4373-11ea-8dca-394ced1ee06a.png)

**Comment by SI-BenHodges** [comment]
sadly that didn't fix it - i thought you had it there but i have tried multiple times since but no luck.

I've even tried to switch off the firewall completely to rule that out.

it couldn't be a redirection issue could it? what rules do you have on your app gateway?

**Comment by NikolaiThingnesLeira** [comment]
Paths: `/.well-known/acme-challenge/*`

Target: `https://<YourStorageAccount>.blob.core.windows.ne/<yourBlobContainer>`

When you check your Storage Container, what does it say under `Public Access Level`? Here's mine:
![image](https://user-images.githubusercontent.com/8503265/73524146-d01bca80-440c-11ea-87b5-e232fbd01897.png)

**Comment by SI-BenHodges** [comment]
that's the thing i sent you earlier:

![image](https://user-images.githubusercontent.com/54708648/73527171-7f0ad700-440a-11ea-9b93-d139c2f25d68.png)

i'm not sure how it can't have access when it is writing files to this folder

**Comment by NikolaiThingnesLeira** [comment]
Ah, you're right, sorry!

And it's an external party (Let's Encrypt) that's trying to access it, not the ACME-PS module itself. My last suggestion:
```
# Set the Blob Content type so it shows in a browser
$blobProperties = @{
    "ContentType" = "text/plain; charset=utf-8"
}
```
This sets a hash table which specifies the file type in the storage blob, making it viewable in a browser.  Then change
`Set-AzureStorageBlobContent -File $fileName -Container "public" -Context $ctx -Blob $blobName`
to
`Set-AzureStorageBlobContent -File $fileName -Container "public" -Context $ctx -Blob $blobName -Properties $blobProperties`

**Comment by Mik4sa** [comment]
In case anyone is struggling here too. I followed @Gholie and migrated the script to Az modules and made a pull request. It worked then for me without any problems (I'm not behind a firewall).
